SkiaCanvas: class extension.
- on github i get the error: return style | SWT.SKIA;
Error:  SKIA cannot be resolved or is not a field
So this means, github load a separate SWT-version, where skia is not
implemented.
- so as a workaround: i use the value locally for the moment.